### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by davidwu220** [FdezRomero/request-image-size#11]
I'm having trouble getting it to work. 
Please check out my [source code](https://github.com/davidwu220/dog-breed-masonry/blob/master/src/App.js) on how I implemented it (specifically at line 156-158).
The full error is as follows
> Failed to load https://images.dog.ceo/breeds/affenpinscher/n02110627_12819.jpg:
> No 'Access-Control-Allow-Origin' header is present on the requested resource.
> Origin 'https://davidwu220.github.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any idea how I can fix this?
Thanks!

**Comment by FdezRomero** [comment]
Hi @davidwu220!

Although this package is intended to be used in the backend with Node.js, the error you're having is due to the cross-origin security in the browser. The host you're contacting (`images.dog.ceo`) is missing the `Access-Control-Allow-Origin` header so CORS is not enabled.

I'm guessing this server is not yours, so there's nothing you can do about it (other than running this with Node.js).

Thanks,
Rodrigo

**Comment by davidwu220** [comment]
Got it. Thanks for the reply!
